package com.jancar.radio.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jancar.radio.entity.RadioStation;
import com.jancar.radio.entity.Collection;

import com.jancar.radio.greendao.RadioStationDao;
import com.jancar.radio.greendao.CollectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig radioStationDaoConfig;
    private final DaoConfig collectionDaoConfig;

    private final RadioStationDao radioStationDao;
    private final CollectionDao collectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        radioStationDaoConfig = daoConfigMap.get(RadioStationDao.class).clone();
        radioStationDaoConfig.initIdentityScope(type);

        collectionDaoConfig = daoConfigMap.get(CollectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        radioStationDao = new RadioStationDao(radioStationDaoConfig, this);
        collectionDao = new CollectionDao(collectionDaoConfig, this);

        registerDao(RadioStation.class, radioStationDao);
        registerDao(Collection.class, collectionDao);
    }
    
    public void clear() {
        radioStationDaoConfig.clearIdentityScope();
        collectionDaoConfig.clearIdentityScope();
    }

    public RadioStationDao getRadioStationDao() {
        return radioStationDao;
    }

    public CollectionDao getCollectionDao() {
        return collectionDao;
    }

}
