package com.jancar.radio.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jancar.radio.entity.RadioStation;

import com.jancar.radio.greendao.RadioStationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig radioStationDaoConfig;

    private final RadioStationDao radioStationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        radioStationDaoConfig = daoConfigMap.get(RadioStationDao.class).clone();
        radioStationDaoConfig.initIdentityScope(type);

        radioStationDao = new RadioStationDao(radioStationDaoConfig, this);

        registerDao(RadioStation.class, radioStationDao);
    }
    
    public void clear() {
        radioStationDaoConfig.clearIdentityScope();
    }

    public RadioStationDao getRadioStationDao() {
        return radioStationDao;
    }

}
